import json
import os

def generate_full_migration_sql(json_filepath="editingstyle.json", output_filename="data.sql"):
    """
    Generates a complete SQLite migration file from a JSON file.

    The output SQL file includes table creation statements (schema) and
    all the necessary INSERT statements to populate the tables with data
    from the provided JSON file.

    Args:
        json_filepath (str): The path to the input JSON file.
        output_filename (str): The name for the output SQL migration file.
    """
    try:
        with open(json_filepath, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"❌ Error: The file '{json_filepath}' was not found.")
        return
    except json.JSONDecodeError:
        print(f"❌ Error: Could not decode JSON from '{json_filepath}'. Please check its format.")
        return

    # Start with the schema definition
    sql_commands = [
        "-- SQLite Migration File",
        "-- Generated by a Python script.",
        "-- This file contains the schema and all the data from the JSON file.",
        "",
        "PRAGMA foreign_keys=OFF;",
        "BEGIN TRANSACTION;",
        "",
        "-- Drop tables if they exist for a clean setup.",
        "DROP TABLE IF EXISTS youtube_videos;",
        "DROP TABLE IF EXISTS twitter_videos;",
        "",
        "-- Schema for YouTube videos table.",
        "CREATE TABLE youtube_videos (",
        "    id INTEGER PRIMARY KEY AUTOINCREMENT,",
        "    youtube_url TEXT NOT NULL UNIQUE",
        ");",
        "",
        "-- Schema for Twitter videos table.",
        "CREATE TABLE twitter_videos (",
        "    id INTEGER PRIMARY KEY AUTOINCREMENT,",
        "    tweet_url TEXT NOT NULL UNIQUE,",
        "    video_url TEXT NOT NULL",
        ");",
        ""
    ]

    # Generate INSERT statements for each record in the JSON data
    for record in data:
        # Check if it's a YouTube record
        if 'youtube_url' in record and record.get('youtube_url'):
            # Escape single quotes in the URL to prevent SQL errors
            url = record['youtube_url'].replace("'", "''")
            sql_commands.append(f"INSERT INTO youtube_videos (youtube_url) VALUES ('{url}');")
        
        # Check if it's a Twitter/X record
        elif 'tweet_url' in record and record.get('tweet_url'):
            # Escape single quotes in URLs
            tweet_url = record['tweet_url'].replace("'", "''")
            video_url = record.get('video_url', '').replace("'", "''") # Use .get() for safety
            sql_commands.append(f"INSERT INTO twitter_videos (tweet_url, video_url) VALUES ('{tweet_url}', '{video_url}');")

    # Add commit statement to finalize the transaction
    sql_commands.append("\nCOMMIT;")

    # Write all commands to the output file
    try:
        with open(output_filename, 'w') as f:
            f.write("\n".join(sql_commands))
        print(f"✅ Successfully created the full migration file: '{os.path.abspath(output_filename)}'")
    except IOError as e:
        print(f"❌ Error: Could not write to file '{output_filename}'. Reason: {e}")

if __name__ == "__main__":
    generate_full_migration_sql()